version: '3.8'

services:
  hbase:
    image: "${HBASE_IMAGE}"
    container_name: hbase-docker
    hostname: hbase-docker
    volumes:
      - ./utils:/opt/utils
      - /Users/andor/tmp/data-store/hbase:/data-store/hbase
      - ./conf1/hbase-site.xml:${HBASE_CONF_DIR}/hbase-site.xml
      - ./conf1/zoo.cfg:${HBASE_CONF_DIR}/zoo.cfg

  hbase2:
    image: "${HBASE_IMAGE}"
    container_name: hbase-docker-2
    hostname: hbase-docker-2
    volumes:
      - ./utils:/opt/utils
      - /Users/andor/tmp/data-store/hbase:/data-store/hbase
      - ./conf2/hbase-site.xml:${HBASE_CONF_DIR}/hbase-site.xml
      - ./conf2/zoo.cfg:${HBASE_CONF_DIR}/zoo.cfg

